language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install numpy>=1.16.4 keras>=2.2.5 tensorflow>=1.14.0 scikit-learn>=0.21.2
  - pip install -e .
# command to run tests
script: pytest tests.py